apiVersion: apps/v1
kind: Deployment
metadata:
  name: dersg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dersg
  template:
    metadata:
      labels:
        app: dersg
    spec:
      containers:
      - image: okteto.dev/dersg:latest
        name: dersg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2edd5b31-3bbd-45e7-a742-d5cf0b2f59d7"
        - name: Vless_Path
          value: "/ray"
        - name: Vmess_UUID
          value: "2edd5b31-3bbd-45e7-a742-d5cf0b2f59d7"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
